apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx-sftp
  name: nginx-sftp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx-sftp
  template:
    metadata:
      labels:
        run: nginx-sftp
    spec:
      volumes:
      - name: webdata
        persistentVolumeClaim:
          claimName: sftp-pvc
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: webdata
          mountPath: "/usr/share/nginx/html"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftp-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: sfs-storage-class
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-sftp-svc
spec:
  selector:
    run: nginx-sftp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  creationTimestamp: "2020-07-17T07:36:26Z"
  generation: 1
  name: nginx-sftp-ing
spec:
  rules:
  - host: nginx-sftp.caas-cnp-apps.com.intraorange
    http:
      paths:
      - backend:
          serviceName: nginx-sftp-svc
          servicePort: 80
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
